### ISSUE TITLE
No resource or method named `pg_user' for `Chef::Recipe "postgresql"'

### ISSUE THREAD

**Issue by klrmn** [maigfrga/django-vagrant-chef#1]
i found the string pg_user in a bunch of comments in READMEs in the repo, but not in any of the code files. i am using django-vagrant-chef because i'm new to chef and don't know how to diagnose things like this.

================================================================================
Recipe Compile Error in /tmp/vagrant-chef-1/chef-solo-2/cookbooks/django/recipes/default.rb
================================================================================

NoMethodError
-------------
No resource or method named `pg_user' for `Chef::Recipe "postgresql"'

Cookbook Trace:
---------------
  /tmp/vagrant-chef-1/chef-solo-2/cookbooks/django/recipes/postgresql.rb:4:in `from_file'
  /tmp/vagrant-chef-1/chef-solo-2/cookbooks/django/recipes/default.rb:1:in `from_file'

Relevant File Content:
----------------------
/tmp/vagrant-chef-1/chef-solo-2/cookbooks/django/recipes/postgresql.rb:

  1:  include_recipe 'postgresql::server'
  2:  include_recipe 'postgresql::client'
  3:  
  4>> pg_user node['django']['postgresql']['user'] do
  5:    privileges superuser: true, createdb: true, login: true
  6:    password node['django']['postgresql']['password']
  7:  end
  8:  
  9:  pg_database node['django']['postgresql']['database'] do
 10:    owner node['django']['postgresql']['user']
 11:    encoding node['django']['postgresql']['encoding']
 12:    template 'template0'
 13:    locale 'en_US.UTF8'

[2015-03-29T02:18:44+00:00] ERROR: Running exception handlers
[2015-03-29T02:18:44+00:00] ERROR: Exception handlers complete
[2015-03-29T02:18:44+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-03-29T02:18:44+00:00] ERROR: No resource or method named `pg_user' for `Chef::Recipe "postgresql"'
[2015-03-29T02:18:45+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by maigfrga** [comment]
Hi, it is a bug, I will give it a look as soon as posible

**Comment by klrmn** [comment]
Great! Thank you =)

**Comment by klrmn** [comment]
someone who knows more about chef than i do suggests that https://github.com/phlipper/chef-postgresql/commit/b87943cb4ea98868c6df060057bfeefa416fcc3d in the upstream repo is what caused the problem.

**Comment by maigfrga** [comment]
I have pushed a new version, the postgresql thin has been solved and now it has gunicorn.

I only works on ubuntu becauset its upstart support for gunicorn.

There is as well a folder test with a vagrant example an django project.

**Comment by maigfrga** [comment]
I found that sometimes gunicorn does not start automatically , you can ssh vagrant and restart it:

vagrant ssh

sudo -i

service ds3 restart

**Comment by klrmn** [comment]
it may be the thing to update test/Vagrantfile with the chef.json in http://www.maigfrga.ntweb.co/entorno-de-desarrollo-vagrant-con-django-y-ubuntu/ =)
